# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7decff18a623f2cb0df6f9f042a311195ddc6053545d86225d0f39073c98200610c8272e54a477591b29de9759aa0074c2ccfde971fa5f0eadaab4df35486b9e

test:
  secret_key_base: 092f07740f4afe0458dcdb44d70d962a2776e482eb2826fdd4755c79c28d02ab49bc1d8e9c3aeed68ce9a29fa06d1cd2c244bd52ac76b0af3db3a286efd81ba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
